### ISSUE TITLE
Laravel 5 trouble install

### ISSUE THREAD

**Issue by netwarp** [closca/sonus#2]
Hello, 
I have troubles to install the package on Laravel 5.
You can see the error message here.
Could you please tell me what's wrong with it ?
Thanks a lot.

composer.json
{
"require": {
        "laravel/framework": "5.0.*",
        "laravelcollective/html": "~5.0",
        "rtconner/laravel-tagging": "~1.0.2",
        "closca/sonus": "dev-master"
    }
}

Your requirements could not be resolved to an installable set of packages.                                      

  Problem 1  
    - Conclusion: remove laravel/framework v5.0.27  
    - Conclusion: don't install laravel/framework v5.0.27  
    - Conclusion: don't install laravel/framework v5.0.26  
    - Conclusion: don't install laravel/framework v5.0.25  
    - Conclusion: don't install laravel/framework v5.0.24  
    - Conclusion: don't install laravel/framework v5.0.23  
    - Conclusion: don't install laravel/framework v5.0.22  
    - Conclusion: don't install laravel/framework v5.0.21  
    - Conclusion: don't install laravel/framework v5.0.20  
    - Conclusion: don't install laravel/framework v5.0.19  
    - Conclusion: don't install laravel/framework v5.0.18  
    - Conclusion: don't install laravel/framework v5.0.17  
    - Conclusion: don't install laravel/framework v5.0.16  
    - Conclusion: don't install laravel/framework v5.0.15  
    - Conclusion: don't install laravel/framework v5.0.14  
    - Conclusion: don't install laravel/framework v5.0.13  
    - Conclusion: don't install laravel/framework v5.0.12  
    - Conclusion: don't install laravel/framework v5.0.11  
    - Conclusion: don't install laravel/framework v5.0.10  
    - Conclusion: don't install laravel/framework v5.0.9  
    - Conclusion: don't install laravel/framework v5.0.8  
    - Conclusion: don't install laravel/framework v5.0.7  
    - Conclusion: don't install laravel/framework v5.0.6  
    - Conclusion: don't install laravel/framework v5.0.5  
    - Conclusion: don't install laravel/framework v5.0.4  
    - Conclusion: don't install laravel/framework v5.0.3  
    - Installation request for closca/sonus dev-master -> satisfiable by closca/sonus[dev-master].  
    - Conclusion: don't install laravel/framework v5.0.2  
    - Conclusion: don't install laravel/framework v5.0.1  
    - closca/sonus dev-master requires illuminate/support 4.2.\* -> satisfiable by illuminate/support[v4.2.1, v4 
.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].  
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.0  
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.0  
    - Installation request for laravel/framework 5.0.\* -> satisfiable by laravel/framework[v5.0.0, v5.0.1, v5.0 
.10, v5.0.11, v5.0.12, v5.0.13, v5.0.14, v5.0.15, v5.0.16, v5.0.17, v5.0.18, v5.0.19, v5.0.2, v5.0.20, v5.0.21, 
 v5.0.22, v5.0.23, v5.0.24, v5.0.25, v5.0.26, v5.0.27, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9].

**Comment by closca** [comment]
The package is not updated to laravel 5. Maybe in future. I am opened for a
pull request.
Pe 11 apr. 2015 20:48, "resethread" notifications@github.com a scris:

**Comment by closca** [comment]
From now laravel 5 is available
