### ISSUE TITLE
how to use codec

### ISSUE THREAD

**Issue by ArbindJain** [closca/sonus#3]
i want to covert mp3 to ogg
ffmpeg command line is ffmpeg -y -i sample.mp3 -acodec libvorbis -aq 50 sample.ogg
how to achive this using sonus

**Comment by netwarp** [comment]
Did you success to install sonus with Composer in your Laravel projetct ?

**Comment by closca** [comment]
I rewrite again. FOr now only Laravel 4 is supported.
As for ArbindJain request
try this
Sonus::convert()->input('sample.mp3')->output('sample.ogg')->go(' -acodec libvorbis -aq 50');

**Comment by closca** [comment]
I don;t have the time to make it for laravel 5. Actualy just a few days ago I started first serious project on Laravel 5. Is possible in future to migrate but not in near future.

Thanks
PS: anyone could make a pull request, and also i can give permissions to the repo
